### PR TITLE
Fix bug (cannot fill shopping cart)

### PR DESCRIPTION
**Pull request by priojk**
Without this change, DOL_DOCUMENT_ROOT is not defined and trying to place an item in the shopping cart results in an error.

### CODE REVIEW

**Comment by eldy** [comment]
@Daoud-mohamed is this fix ok for you ?

**Comment by Daoud-mohamed** [comment]
@priojk @eldy  I think this issue is due to not loading the environment for pages of type _SERVICE_PAGE_ . 
This issue is resolved by this PR https://github.com/Dolibarr/dolibarr/pull/30245  in the Dolibarr repository.

**Comment by eldy** [comment]
> @priojk @eldy  I think this issue is due to not loading the environment for pages of type _SERVICE_PAGE_ . 
> This issue is resolved by this PR https://github.com/Dolibarr/dolibarr/pull/30245  in the Dolibarr repository.
> 

So @priojk can you check if after having got the last version and regenerating the website pages (you have a button for this on the website top toolbar), you still have the trouble (you should not) with no need foe this pr ?

**Comment by priojk** [comment]
Thanks for looking into this. Actually, I installed from the latest Git resources about a week ago. Since the mentioned PR was merged already on July 3rd, it was already included.

Anyway, I just checked again: if I do not add ' require "master.inc.php";' at the beginning of page 57 (_service_page_Ajax) I cannot add an item to the cart and a popup just says "Error".

Since I did not yet dig very deep into this project, I cannot fully exclude configuration issues or other stupid things on my side.

**Comment by Daoud-mohamed** [comment]
@priojk 
You can check the generated page located at \dolibarr\documents\website\__WEBSITEREF__\page57.tpl.php

It should start like that:

image

If it does not start with an include for master.inc.php, you should get the latest version of Dolibarr and the marketplace module, then either reimport the template or reload the marketplace module to regenerate the template pages.

**Comment by priojk** [comment]
I just tested this with the very latest Dolibarr v20 and the latest marketplace module, including the three not yet merged PRs. I also reloaded the marketplace module and re-generated the files.

And I still have the error message when trying to fill the shopping cart. The page57 looks like this:

image

By manually changing the include of master.inc.php, I can fill the shopping cart and can complete the full checkout procedure including the payment.

Additional question: is the search supposed to be working already? There I have problems as well, but this may be unrelated and I need to dig deeper to better understand the problem. -> could clarify this, there were three lines to fix to make it work. What would be the best way to submit these fixes? Since they happen on the website, it seems not optimal to submit a patch to the sql file containing the website.

**Comment by Daoud-mohamed** [comment]
@priojk

Several PRs used in this template are still in the develop branch of dolibarr, and they will probably be merged in V21 of Dolibarr. To resolve the issue, switching to the develop branch of Dolibarr should help.

Regarding the search functionality, it works well and now supports multilingual search. However, it also depends on a [PR ](https://github.com/Dolibarr/dolibarr/pull/31070)currently in Dolibarr’s develop branch.

Since this template is still under testing, and we've made some core updates to Dolibarr that are also in the develop branch, it is necessary to use the develop version of Dolibarr until the next release.

If you continue to encounter errors after switching both dolibarr and dolibarr-foundation to the develop branch, feel free to submit fixes by providing the SQL file containing  the website data.

**Comment by priojk** [comment]
@Daoud-mohamed 
Thanks for the clarification about the system requirements - I wasn't aware of the dependency on the develop branch of Dolibarr, but it makes perfect sense. Anyways, this online marketplace provides an amazing functionality.

**Pull request closed without merging**
